language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "iojs"

before_install:
  - sudo apt-get install build-essential
  - g++ --version
  - export CXXFLAGS="-std=c++0x $CXXFLAGS"

before_script:
  - if [ "`nvm current`" < "system" ]; then N=`which node`; D=`dirname $N`; ln -s $D/../lib/node_modules/npm/bin/node-gyp-bin/node-gyp; fi
